### ISSUE TITLE
Make death circle

### ISSUE THREAD

**Issue by IceMage144** [IceMage144/Pirate-ship-battles#40]

**Comment by LuizGyro** [comment]
Initially static.
Once we implement the final state, it will start overlapping with a part of the map, and after a certain amount of time passes, the circle starts decreasing.

**Comment by pedro823** [comment]
In file death_circle.js:

```javascript
// Note that, although it is called  "death  circle",  the  actual  circle  area
// represents the safe zone for the player. Only  the  outer  area  actually  is
// harmful to the player.
...

module.exports = class DeathCircle {
```

???????

If you need a three-liner comment to explain that the variable actually means another thing, why not just change the variable name?

```javascript
module.exports = class SafeZone {
```

**Comment by pedro823** [comment]
@IceMage144 @GuilhermeVieira @PaiZuZe could you all take a look?

**Comment by GuilhermeVieira** [comment]
> @IceMage144 @GuilhermeVieira @PaiZuZe could you all take a look?

Thanks for the suggestion. The variable names have been changed.

**Comment by PaiZuZe** [comment]
Death circle, now safe zone has been finished
