### ISSUE TITLE
Add visual representation for Safe Zone

### ISSUE THREAD

**Issue by LuizGyro** [IceMage144/Pirate-ship-battles#62]
Suggestion: make line thicker, change its color to black and make it semi-transparent, so the sea looks darken on dangerous areas.

**Comment by GuilhermeVieira** [comment]
The suggested idea unfortunately doesn't work. It makes the line thicker to the ellipse inside too. We'll have to work out something else.

![image](https://user-images.githubusercontent.com/9259947/46742936-6b1fec80-cc7e-11e8-9d06-121973bf3e69.png)

**Comment by GuilhermeVieira** [comment]
Another suggestion is using fog effect of WebGL.

**Comment by GuilhermeVieira** [comment]
Done using WebGL
